name: Update resume

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout...
        uses: actions/checkout@v4.2.2
      - name: Install...
        run: sh install.sh
      - name: Render resume...
        run: node render.js
      - name: Setup Pages...
        uses: actions/configure-pages@v5.0.0
      - name: Upload artifact...
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: './docs'
      - name: Deploy to GitHub Pages...
        uses: actions/deploy-pages@v4.0.5
